# Generated by Django 5.0.4 on 2024-04-23 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evrgreen', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='customerprofile',
            old_name='customer_id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='merchantprofile',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent_category',
        ),
        migrations.RemoveField(
            model_name='merchantprofile',
            name='last_name',
        ),
    ]
